# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeshark < Formula
  desc ""
  homepage "https://github.com/kubeshark/kubeshark"
  version "39.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubeshark/kubeshark/releases/download/39.6/kubeshark_39.6_darwin_arm64.tar.gz"
      sha256 "1614373273a0e1bf1462e0816449784cb15d61280a1701ce3e38fb6ccc297d21"

      def install
        bin.install "kubeshark"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshark/kubeshark/releases/download/39.6/kubeshark_39.6_darwin_amd64.tar.gz"
      sha256 "054444394756db1ea981e3669ecd8bc441a3415f5c1f54c28d08e431b1b4a3a3"

      def install
        bin.install "kubeshark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshark/kubeshark/releases/download/39.6/kubeshark_39.6_linux_arm64.tar.gz"
      sha256 "f002c32108c768220d1d0f04ad8a78830924e95694dd5d79849efc37dd493649"

      def install
        bin.install "kubeshark"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshark/kubeshark/releases/download/39.6/kubeshark_39.6_linux_amd64.tar.gz"
      sha256 "d1cb3ccaff5eff8dfaf2c6915dde365239dd13cc0d59ae2e5cd01e93bd4cad62"

      def install
        bin.install "kubeshark"
      end
    end
  end
end
